version: '3'
silent: true
dotenv: ['.env']
tasks:
  test:
    desc: "🧪 Run tests"
    cmds:
      - task: venv
      - echo "Running test suite..."
      - python -m unittest
      - echo "Analyzing code with mypy..."
      - mypy source_code/ --strict
  start:
    desc: "🚀 Run the application"
    dir: docker
    cmds:
      - docker-compose up --build -d
  stop:
    desc: "🛑 Stop the application"
    dir: docker
    cmds:
      - docker-compose down
  install:
    desc: "🫴 Install requirements"
    cmds:
      - task: venv
      - pip install -r requirements.txt
      - echo "Requirements installed"
  venv:
    internal: true
    cmds:
      - cmd: powershell ./.venv/Scripts/activate.bat
        platforms: [ windows ]
      - cmd: ./venv/Scripts/activate
        platforms: [ darwin, linux ]
  default:
    cmds:
      - task -l --sort none