version: '3'
silent: true
dotenv: ['.env']
tasks:
  test:
    desc: "🧪 Run tests"
    cmds:
      - echo "Running test suite..."
      - .venv/bin/python -m unittest
      - echo "Analyzing code with mypy..."
      - .venv/bin/mypy source_code/ --strict
  start:
    desc: "🚀 Run the application"
    dir: docker
    cmds:
      - docker-compose up --build -d
  stop:
    desc: "🛑 Stop the application"
    dir: docker
    cmds:
      - docker-compose down
  install:
    desc: "🫴 Install requirements"
    cmds:
      - .venv/bin/pip install -r requirements.txt
      - echo "Requirements installed"
  default:
    cmds:
      - task -l --sort none