version: '3'
services:
  toolify:
    container_name: toolify
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: toolify
    ports:
      - "5000:5000"
    env_file:
      - ../.env
