- uses: actions/checkout@v2

- name: Setup Python version
  uses: actions/setup-python@v2
  with:
  python-version: 3.8

- name: Create and start virtual environment
  run: |
    python3 -m venv venv
    source venv/bin/activate

- name: Install dependencies
  run: pip install -r requirements.txt

- name: Execute application
  run: python3 app.py
